version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tomate_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - tomato-net

  db:
    image: mysql:8.0
    container_name: mysql-tomate
    restart: always
    environment:
      MYSQL_DATABASE: tomate_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tomato-net

volumes:
  db_data:

networks:
  tomato-net: